---
title: "JCOPE ANALYSIS"
author: "Patrick Spauster"
date: "2023-09-18"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(googlesheets4)
library(janitor)
library(RPublica) #https://www.r-project.org/nosvn/pandoc/RPublica.html
library(curl)
library(httr)
library(jsonlite)
library(RSocrata)

knitr::opts_chunk$set(echo = TRUE)
```

https://data.ny.gov/Transparency/Lobbyist-Bi-Monthly-Reports-Beginning-2019/t9kf-dqbc
https://data.ny.gov/api/views/t9kf-dqbc/files/0492a388-f728-41cd-bd61-b72c4cfd45fa?download=true&filename=COELIG_LobbyistBiMonthlyReports_DataDictionary.pdf
```{r}

clients <- read_csv("https://data.ny.gov/resource/t9kf-dqbc.csv?$select=contractual_client_name,COUNT(contractual_client_name)&$group=contractual_client_name&$LIMIT=100000")

lobbyists <- read_csv("https://data.ny.gov/resource/t9kf-dqbc.csv?$select=principal_lobbyist_name,COUNT(principal_lobbyist_name)&$group=principal_lobbyist_name&$LIMIT=100000")

beneficial <- read_csv("https://data.ny.gov/resource/t9kf-dqbc.csv?$select=beneficial_client_name,COUNT(beneficial_client_name)&$group=beneficial_client_name&$LIMIT=100000")

beneficial_client_names <- c('TAXPAYERS FOR AN AFFORDABLE NY, INC.;' , 'Homeowners for an Affordable New York LLC;' , 'REAL ESTATE BOARD OF NEW YORK, INC.;' , 'COMMUNITY HOUSING IMPROVEMENT PROGRAM, INC.;' , 'RENT STABILIZATION ASSOCIATION OF NYC, INC.;', 'ASSOCIATION OF REALTORS (NYS);')

principal_lobbyist_names <- c('TAXPAYERS FOR AN AFFORDABLE NY, INC.','Homeowners for an Affordable New York LLC','REAL ESTATE BOARD OF NEW YORK, INC.','COMMUNITY HOUSING IMPROVEMENT PROGRAM, INC.' , 'RENT STABILIZATION ASSOCIATION OF NYC, INC.', "ASSOCIATION OF REALTORS (NYS)")


```

also get RSA, Association of Realtors, CHIP


```{r}

url <- URLencode("https://data.ny.gov/resource/t9kf-dqbc.csv?contractual_client_name=REAL ESTATE BOARD OF NEW YORK, INC.&$limit=20000")

rebny <- read_csv(url)

taxpayers <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?contractual_client_name=TAXPAYERS FOR AN AFFORDABLE NY, INC.&$limit=20000"
))

homeowners <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?contractual_client_name=Homeowners for an Affordable New York LLC&$limit=20000"
))

NYSAR <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?contractual_client_name=ASSOCIATION OF REALTORS (NYS)&$limit=200000"
))

combined <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?$where=beneficial_client_name = 'TAXPAYERS FOR AN AFFORDABLE NY, INC.;' OR beneficial_client_name = 'Homeowners for an Affordable New York LLC;' OR beneficial_client_name = 'REAL ESTATE BOARD OF NEW YORK, INC.;' OR beneficial_client_name = 'COMMUNITY HOUSING IMPROVEMENT PROGRAM, INC.;' OR beneficial_client_name = 'RENT STABILIZATION ASSOCIATION OF NYC, INC.;' OR principal_lobbyist_name = 'TAXPAYERS FOR AN AFFORDABLE NY, INC.' OR principal_lobbyist_name = 'Homeowners for an Affordable New York LLC' OR principal_lobbyist_name='REAL ESTATE BOARD OF NEW YORK, INC.' OR principal_lobbyist_name = 'COMMUNITY HOUSING IMPROVEMENT PROGRAM, INC.' OR principal_lobbyist_name = 'RENT STABILIZATION ASSOCIATION OF NYC, INC.' &$LIMIT= 100000"))


```

```{r}
combined_clean <- combined %>% 
  separate(unique_id, sep = "-", into = as.character(1:11), remove = F)
```


```{r}


expenses <- combined %>% 
  group_by(form_submission_id) %>% 
  summarize(client = first(beneficial_client_name),
            compensation = max(compensation),
            expenses_reium = max(reimbursed_expenses),
            non_lobbying_expense = max(lobbying_expenses_for_non),
            expenses_total_item = sum(itemized_expenses, na.rm = T),
            year = first(reporting_year)
            )

expenses_year_org_sum <- expenses %>% 
  group_by(year, client) %>% 
  summarize(total_compensation = sum(compensation),
            total_reium_expenses = sum(expenses_reium),
            total_nonlobb_expenses = sum(non_lobbying_expense),
            total_item_expenses = sum(expenses_total_item)
            )




expenses_year_org_sum %>% ungroup() %>%   summarize(
            total_compensation = sum(total_compensation),
            total_reium_expenses = sum(total_reium_expenses),
            total_nonlobb_expenses = sum(total_nonlobb_expenses),
            total_item_expenses = sum(total_item_expenses)
            )

expenses_year_org_sum %>% ungroup() %>% group_by(client) %>%    summarize(
            total_compensation = sum(total_compensation),
            total_reium_expenses = sum(total_reium_expenses),
            total_nonlobb_expenses = sum(total_nonlobb_expenses),
            total_item_expenses = sum(total_item_expenses)
            )
  
  expenses_year_org_sum %>%  summarize(
            total_compensation = sum(total_compensation),
            total_reium_expenses = sum(total_reium_expenses),
            total_nonlobb_expenses = sum(total_nonlobb_expenses),
            total_item_expenses = sum(total_item_expenses)
            )
  

```



```{r}

combined %>% group_by(focus_identifying_number) %>% summarize(n= n(), dollars = sum(itemized_expenses, na.rm = T)) %>% arrange(desc(dollars))

combined %>% group_by(expense_purpose) %>% summarize(n= n(), dollars = sum(itemized_expenses, na.rm = T)) %>% arrange(desc(dollars))

combined %>% group_by(party_name) %>% summarize(n= n(), dollars = sum(itemized_expenses, na.rm = T)) %>% arrange(desc(n))

combined %>% group_by(person_lobbied) %>% summarize(n= n(), dollars = sum(itemized_expenses, na.rm = T)) %>% arrange(desc(n))


combined %>% group_by(lobbying_subjects) %>% summarize(n= n()) %>% arrange(desc(n))


combined %>% filter(str_detect(focus_identifying_number, "S305|good cause|S3082|A5573")) %>% count(focus_identifying_number)

```


```{r}

good_cause <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?$where=focus_identifying_number = 'S305' OR focus_identifying_number = 'Intended introduction regarding good cause eviction' OR focus_identifying_number = 'S3082' OR focus_identifying_number = 'A5573'&$limit=200000"
))

good_cause %>% pull(beneficial_client_name) %>% unique

good_cause %>% filter(beneficial_client_name %in% beneficial_client_names) %>% count(person_lobbied) %>% arrange(desc(n))
good_cause %>% filter(beneficial_client_name %in% beneficial_client_names) %>% count(party_name) %>% arrange(desc(n))

good_cause_spending <- good_cause %>% 
  group_by(form_submission_id) %>% 
  summarize(compensation = max(compensation),
            expenses_reium = max(reimbursed_expenses),
            expenses_total_item = sum(itemized_expenses),
            non_lobbying_expense = max(lobbying_expenses_for_non),
            client = first(beneficial_client_name)
            )

good_cause_sum <- good_cause_spending %>% 
  group_by(client) %>% 
  summarize(total_compensation = sum(compensation),
            total_reium_expenses = sum(expenses_reium),
            total_nonlobb_expenses = sum(non_lobbying_expense),
            total_item_expenses = sum(expenses_total_item))


```


```{r}

rent_reg <- read_csv(URLencode(
  "https://data.ny.gov/resource/t9kf-dqbc.csv?$where=focus_identifying_number = 'rent regulation' OR focus_identifying_number = 'Rent Guidelines Board' &$limit=200000"
))


```

















```{r}

sof <- read_sheet("https://docs.google.com/spreadsheets/d/1G_5dkzSlSvbVwM7Q-NItgntBawFXDoZaFoq4XPoTSLE/edit#gid=78477068", 
                  sheet = "Sources of Funding",
                  col_types = "ccccDd????") %>% 
  clean_names()

```

```{r}
sof %>% 
  group_by(name) %>% 
  summarize(total_contributions = sum(amount_of_contribution, na.rm = T),
            )

sof %>% 
  filter(!is.na(amount_of_contribution)) %>% 
  count(amount_of_contribution == 0)
```





